export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD'; 

export const REQUEST_BOTS_PENDING = 'REQUEST_BOTS_PENDING';
export const REQUEST_BOTS_SUCCESS = 'REQUEST_BOTS_SUCCESS';
export const REQUEST_BOTS_FAILED = 'REQUEST_BOTS_FAILED';